# Generated by Django 3.1.5 on 2021-01-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='perofchem',
            new_name='rate',
        ),
    ]
